version: '3.1'

services:
  app:
    container_name: customer-backend
    image: customer-backend
    build: 
      context: .
    ports:
      - "4001:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok

networks:
    default:
        external:
            name: testing-dev


